/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 01-feb.-2021 15:51:39 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

USE `heroku_7dce0ea8bf748df`;

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS Atm CASCADE
;

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS Cuenta CASCADE
;

DROP TABLE IF EXISTS Operacion CASCADE
;

DROP TABLE IF EXISTS Operacion_Cliente CASCADE
;

DROP TABLE IF EXISTS TarjetaDebito CASCADE
;

DROP TABLE IF EXISTS TarjetaDebito_Atm CASCADE
;

/* Create Tables */

CREATE TABLE Atm
(
	idAtm VARCHAR(50) NOT NULL,
	disponible BOOL NOT NULL,
	dineroActual BIGINT NOT NULL,
	montoMinimoRequerido BIGINT NOT NULL,
	CONSTRAINT PK_Atm PRIMARY KEY (idAtm ASC)
)

;

CREATE TABLE Cliente
(
	idCliente BIGINT NOT NULL,
	direccion VARCHAR(50) NOT NULL,
	nombre VARCHAR(30) NOT NULL,
	telefono INT NOT NULL,
	CONSTRAINT PK_Cliente PRIMARY KEY (idCliente ASC)
)

;

CREATE TABLE Cuenta
(
	idCuenta VARCHAR(50) NOT NULL,
	contraseña MEDIUMINT NOT NULL,
	numero BIGINT NOT NULL,
	saldo DOUBLE(10,2) NOT NULL,
	idTarjeta VARCHAR(50) NOT NULL,
	idCliente BIGINT NOT NULL,
	numeroTarjeta BIGINT NOT NULL,
	montoRetiradoPorDia BIGINT NOT NULL,
	montoMaximoDiario BIGINT NOT NULL,
	CONSTRAINT PK_Cuenta PRIMARY KEY (idCuenta ASC, numero ASC)
)

;

CREATE TABLE Operacion
(
	idOperacion VARCHAR(50) NOT NULL,
	codigo_confirmacion INT NOT NULL,
	tipo VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Operacion PRIMARY KEY (idOperacion ASC)
)

;

CREATE TABLE Operacion_Cliente
(
	idOperacion VARCHAR(50) NOT NULL,
	idCliente BIGINT NOT NULL,
	fechaOperacion TIMESTAMP(6) NOT NULL,
	idCuentaAbonada VARCHAR(50) NULL,
	Valor BIGINT NULL,
	idOperacion_Cliente VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Operacion_Cliente PRIMARY KEY (idOperacion_Cliente ASC)
)

;

CREATE TABLE TarjetaDebito
(
	idTarjeta VARCHAR(50) NOT NULL,
	numero BIGINT NOT NULL,
	contraseña SMALLINT NOT NULL,
	numeroIntentos SMALLINT NOT NULL,
	fecha_expiracion DATE NOT NULL,
	CONSTRAINT PK_TarjetaDebito PRIMARY KEY (idTarjeta ASC, numero ASC)
)

;

CREATE TABLE TarjetaDebito_Atm
(
	idTarjetaDebito VARCHAR(50) NOT NULL,
	idAtm VARCHAR(50) NOT NULL,
	numeroTarjeta BIGINT NOT NULL,
	idTarjeta VARCHAR(50) NULL,
	CONSTRAINT PK_TarjetaDebito_Atm PRIMARY KEY (idTarjetaDebito ASC, idAtm ASC, numeroTarjeta ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Cliente 
 ADD CONSTRAINT CK_idCliente CHECK (idCliente > 0)
;

ALTER TABLE Cuenta 
 ADD INDEX IXFK_Cuenta_Cliente (idCliente ASC)
;

ALTER TABLE Cuenta 
 ADD INDEX IXFK_Cuenta_TarjetaDebito (idTarjeta ASC)
;

ALTER TABLE Cuenta 
 ADD INDEX IXFK_Cuenta_TarjetaDebito_02 (idTarjeta ASC, numeroTarjeta ASC)
;

ALTER TABLE Cuenta 
 ADD INDEX IXFK_Cuenta_TarjetaDebito_03 (idTarjeta ASC, numeroTarjeta ASC)
;

ALTER TABLE Operacion_Cliente 
 ADD INDEX IXFK_Operacion_Cliente_Cliente (idCliente ASC)
;

ALTER TABLE Operacion_Cliente 
 ADD INDEX IXFK_Operacion_Cliente_Operacion (idOperacion ASC)
;

ALTER TABLE TarjetaDebito_Atm 
 ADD INDEX IXFK_TarjetaDebito_Atm_Atm (idAtm ASC)
;

ALTER TABLE TarjetaDebito_Atm 
 ADD INDEX IXFK_TarjetaDebito_Atm_TarjetaDebito (idTarjeta ASC, numeroTarjeta ASC)
;

ALTER TABLE TarjetaDebito_Atm 
 ADD INDEX IXFK_TarjetaDebito_Atm_TarjetaDebito_02 (idTarjeta ASC, numeroTarjeta ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE Cuenta 
 ADD CONSTRAINT FK_Cuenta_Cliente
	FOREIGN KEY (idCliente) REFERENCES Cliente (idCliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Cuenta 
 ADD CONSTRAINT FK_Cuenta_TarjetaDebito
	FOREIGN KEY (idTarjeta, numeroTarjeta) REFERENCES TarjetaDebito (idTarjeta,numero) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Operacion_Cliente 
 ADD CONSTRAINT FK_Operacion_Cliente_Cliente
	FOREIGN KEY (idCliente) REFERENCES Cliente (idCliente) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Operacion_Cliente 
 ADD CONSTRAINT FK_Operacion_Cliente_Operacion
	FOREIGN KEY (idOperacion) REFERENCES Operacion (idOperacion) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE TarjetaDebito_Atm 
 ADD CONSTRAINT FK_TarjetaDebito_Atm_Atm
	FOREIGN KEY (idAtm) REFERENCES Atm (idAtm) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE TarjetaDebito_Atm 
 ADD CONSTRAINT FK_TarjetaDebito_Atm_TarjetaDebito
	FOREIGN KEY (idTarjeta, numeroTarjeta) REFERENCES TarjetaDebito (idTarjeta,numero) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
